---

- name: install alert manager
  become: true 
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz 
    dest: /tmp
    remote_src: true

- name: copy alert manager to bin folder 
  become: true 
  copy: 
    src: /tmp/alertmanager-0.21.0.linux-amd64/alertmanager
    dest: /usr/local/bin
    remote_src: true 
    mode: "0777"
    owner: prometheus 
    group: prometheus 

- name: copy alert manager tool to bin folder 
  become: true 
  copy: 
    src: /tmp/alertmanager-0.21.0.linux-amd64/amtool
    dest: /usr/local/bin
    remote_src: true 
    mode: "0777"
    owner: prometheus 
    group: prometheus

- name: make directory alertmanager 
  become: true 
  file: 
    path: /var/lib/alertmanager
    state: directory 
    owner: prometheus
    group: prometheus

- name: Remove Prometheus archive 
  become: true
  file:
    path: /tmp/alertmanager-0.21.0.linux-amd64.tar.gz
    state: absent
  ignore_errors: yes

- name: Remove Prometheus directory 
  become: true
  file:
    path: /tmp/alertmanager-0.21.0.linux-amd64
    state: absent
  ignore_errors: yes

- name: add the alertmanager yaml
  become: true 
  copy: 
    src: alertmanager.yml 
    dest: /etc/prometheus/

- name: configure Alertmanager as a service
  become: true 
  copy: 
    src: alertmanager.service
    dest: /etc/systemd/system/

- name: Reload systemd configuration
  become: true  
  systemd:
    daemon-reload: yes 

- name: Enable Alertmanager service
  become: true 
  systemd: 
    name: alertmanager
    enabled: true 

- name: Start Alertmanager service 
  become: true 
  systemd: 
    name: alertmanager 
    state: started 

- name: add the rules 
  become: true 
  copy: 
    src: rules.yml 
    dest: /etc/prometheus/

- name: restart prometheus 
  become: true 
  systemd: 
    name: prometheus 
    state: restarted