groups:
- name: Down
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 2m
    labels:
      severity: 'critical'
    annotations:
      summary: "Instance  is down"
      description: " of job  has been down for more than 2 minutes."
  
  - alert: HighCpuUsage
    expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
    for: 1m 
    lables: 
      severity: warning
    annotations:
      summary: "High CPU usage on app server"
      description: "The App server is experiencing high CPU usage (>80%)."

  - alert: HighRamUsage
    expr: (100 - ((node_memory_MemFree + node_memory_Buffers + node_memory_Cached) / node_memory_MemTotal * 100)) > 80
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High RAM usage on app server"
      description: "The app server is experiencing high RAM usage (>80%)."