---

- name: Create user Prometheus
  become: true
  user: 
    name: prometheus
    shell: /bin/bash
    createhome: false

- name: create directory in /etc/prometheus
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: create directory in /var/lib/prometheus
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: install node exporter.
  become: true 
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: move binary to /usr/local/bin.
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/prometheus
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0777'
    owner: prometheus
    group: prometheus

- name: move binary to /usr/local/bin.
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/promtool
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0777'
    owner: prometheus
    group: prometheus

- name: Copy Prometheus console files to /etc/prometheus
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/consoles
    dest: /etc/prometheus/
    remote_src: yes
    mode: '0755'
    owner: prometheus
    group: prometheus

- name: Copy Prometheus console files to /etc/prometheus
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/console_libraries
    dest: /etc/prometheus/
    remote_src: yes
    mode: '0755'
    owner: prometheus
    group: prometheus

- name: Remove Prometheus archive 
  become: true
  file:
    path: /tmp/prometheus-2.19.0.linux-amd64.tar.gz
    state: absent
  ignore_errors: yes

- name: Remove Prometheus directory 
  become: true
  file:
    path: /tmp/prometheus-2.19.0.linux-amd64
    state: absent
  ignore_errors: yes

- name: add prometheus yaml file
  become: true
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/

- name: add prometheus.service 
  become: true 
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/

- name: Reload systemd configuration
  become: true  
  systemd:
    daemon-reload: yes 

- name: Enable Prometheus service
  become: true 
  systemd: 
    name: prometheus
    enabled: yes 

- name: Start Prometheus service 
  become: true
  systemd: 
    name: prometheus
    state: started 

